In [1]:
import pandas as pd
import streamlit as st
import requests
import json
import matplotlib.pyplot as plt
import pickle
import shap

Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)

In [2]:
echantillon_clients = pd.read_csv("echantillon_clients.csv", index_col="SK_ID_CURR")

In [3]:
echantillon_clients

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,...,CC_NAME_CONTRACT_STATUS_Sent proposal_MEAN,CC_NAME_CONTRACT_STATUS_Sent proposal_SUM,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MIN,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_COUNT,threshold
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
210332,0.0,1.0,0.0,0.0,540000.0,675000.0,70879.5,675000.0,0.026392,-11246.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.517826
236766,1.0,0.0,0.0,0.0,135000.0,817560.0,30951.0,675000.0,0.031329,-20595.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
174607,1.0,0.0,0.0,1.0,225000.0,601470.0,30838.5,450000.0,0.005084,-15203.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0,0.517826
144965,1.0,0.0,0.0,0.0,112500.0,360000.0,22153.5,360000.0,0.026392,-20534.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
216121,0.0,1.0,0.0,0.0,225000.0,900000.0,29034.0,900000.0,0.026392,-20589.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103460,1.0,0.0,0.0,0.0,360000.0,295776.0,18225.0,234000.0,0.020246,-22869.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
434205,0.0,1.0,0.0,1.0,135000.0,218938.5,22563.0,189000.0,0.010556,-24784.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
382113,1.0,1.0,0.0,2.0,427500.0,450000.0,22500.0,225000.0,0.024610,-14645.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.517826
302364,1.0,0.0,0.0,0.0,135000.0,431280.0,22149.0,360000.0,0.025164,-16727.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0,0.517826
439707,1.0,0.0,1.0,0.0,211500.0,431280.0,22180.5,360000.0,0.010032,-22099.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0,0.517826

In [4]:
echantillon_clients = echantillon_clients.drop(columns=["threshold"])
echantillon_clients

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,...,CC_NAME_CONTRACT_STATUS_Sent proposal_MAX,CC_NAME_CONTRACT_STATUS_Sent proposal_MEAN,CC_NAME_CONTRACT_STATUS_Sent proposal_SUM,CC_NAME_CONTRACT_STATUS_Sent proposal_VAR,CC_NAME_CONTRACT_STATUS_Signed_MIN,CC_NAME_CONTRACT_STATUS_Signed_MAX,CC_NAME_CONTRACT_STATUS_Signed_MEAN,CC_NAME_CONTRACT_STATUS_Signed_SUM,CC_NAME_CONTRACT_STATUS_Signed_VAR,CC_COUNT
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,
210332,0.0,1.0,0.0,0.0,540000.0,675000.0,70879.5,675000.0,0.026392,-11246.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0
236766,1.0,0.0,0.0,0.0,135000.0,817560.0,30951.0,675000.0,0.031329,-20595.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
174607,1.0,0.0,0.0,1.0,225000.0,601470.0,30838.5,450000.0,0.005084,-15203.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26.0
144965,1.0,0.0,0.0,0.0,112500.0,360000.0,22153.5,360000.0,0.026392,-20534.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
216121,0.0,1.0,0.0,0.0,225000.0,900000.0,29034.0,900000.0,0.026392,-20589.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103460,1.0,0.0,0.0,0.0,360000.0,295776.0,18225.0,234000.0,0.020246,-22869.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
434205,0.0,1.0,0.0,1.0,135000.0,218938.5,22563.0,189000.0,0.010556,-24784.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
382113,1.0,1.0,0.0,2.0,427500.0,450000.0,22500.0,225000.0,0.024610,-14645.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0
302364,1.0,0.0,0.0,0.0,135000.0,431280.0,22149.0,360000.0,0.025164,-16727.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,43.0
439707,1.0,0.0,1.0,0.0,211500.0,431280.0,22180.5,360000.0,0.010032,-22099.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95.0

In [16]:
data_client = echantillon_clients.loc[echantillon_clients.index == 210332].to_dict()

In [17]:
data_client

{'CODE_GENDER': {210332: 0.0},
 'FLAG_OWN_CAR': {210332: 1.0},
 'FLAG_OWN_REALTY': {210332: 0.0},
 'CNT_CHILDREN': {210332: 0.0},
 'AMT_INCOME_TOTAL': {210332: 540000.0},
 'AMT_CREDIT': {210332: 675000.0},
 'AMT_ANNUITY': {210332: 70879.5},
 'AMT_GOODS_PRICE': {210332: 675000.0},
 'REGION_POPULATION_RELATIVE': {210332: 0.026392},
 'DAYS_BIRTH': {210332: -11246.0},
 'DAYS_EMPLOYED': {210332: -2539.0},
 'DAYS_REGISTRATION': {210332: -5469.0},
 'DAYS_ID_PUBLISH': {210332: -3405.0},
 'OWN_CAR_AGE': {210332: 3.0},
 'FLAG_MOBIL': {210332: 1.0},
 'FLAG_EMP_PHONE': {210332: 1.0},
 'FLAG_WORK_PHONE': {210332: 1.0},
 'FLAG_CONT_MOBILE': {210332: 1.0},
 'FLAG_PHONE': {210332: 1.0},
 'FLAG_EMAIL': {210332: 1.0},
 'CNT_FAM_MEMBERS': {210332: 2.0},
 'REGION_RATING_CLIENT': {210332: 2.0},
 'REGION_RATING_CLIENT_W_CITY': {210332: 2.0},
 'HOUR_APPR_PROCESS_START': {210332: 20.0},
 'REG_REGION_NOT_LIVE_REGION': {210332: 0.0},
 'REG_REGION_NOT_WORK_REGION': {210332: 0.0},
 'LIVE_REGION_NOT_WORK_REGION': {210332: 0.0},
 'REG_CITY_NOT_LIVE_CITY': {210332: 0.0},
 'REG_CITY_NOT_WORK_CITY': {210332: 0.0},
 'LIVE_CITY_NOT_WORK_CITY': {210332: 0.0},
 'EXT_SOURCE_1': {210332: 0.5067712615026179},
 'EXT_SOURCE_2': {210332: 0.6216133346735832},
 'EXT_SOURCE_3': {210332: 0.3344541255096772},
 'APARTMENTS_AVG': {210332: 0.3619},
 'BASEMENTAREA_AVG': {210332: 0.0781},
 'YEARS_BEGINEXPLUATATION_AVG': {210332: 0.9901},
 'YEARS_BUILD_AVG': {210332: 0.7552},
 'COMMONAREA_AVG': {210332: 0.0227},
 'ELEVATORS_AVG': {210332: 0.36},
 'ENTRANCES_AVG': {210332: 0.3103},
 'FLOORSMAX_AVG': {210332: 0.375},
 'FLOORSMIN_AVG': {210332: 0.2083},
 'LANDAREA_AVG': {210332: 0.0483},
 'LIVINGAPARTMENTS_AVG': {210332: 0.0756},
 'LIVINGAREA_AVG': {210332: 0.3919},
 'NONLIVINGAPARTMENTS_AVG': {210332: 0.0},
 'NONLIVINGAREA_AVG': {210332: 0.2159},
 'APARTMENTS_MODE': {210332: 0.3687},
 'BASEMENTAREA_MODE': {210332: 0.077},
 'YEARS_BEGINEXPLUATATION_MODE': {210332: 0.9901},
 'YEARS_BUILD_MODE': {210332: 0.7583},
 'COMMONAREA_MODE': {210332: 0.0203},
 'ELEVATORS_MODE': {210332: 0.3625},
 'ENTRANCES_MODE': {210332: 0.3103},
 'FLOORSMAX_MODE': {210332: 0.375},
 'FLOORSMIN_MODE': {210332: 0.2083},
 'LANDAREA_MODE': {210332: 0.0462},
 'LIVINGAPARTMENTS_MODE': {210332: 0.0817},
 'LIVINGAREA_MODE': {210332: 0.4083},
 'NONLIVINGAPARTMENTS_MODE': {210332: 0.0},
 'NONLIVINGAREA_MODE': {210332: 0.2286},
 'APARTMENTS_MEDI': {210332: 0.3654},
 'BASEMENTAREA_MEDI': {210332: 0.0778},
 'YEARS_BEGINEXPLUATATION_MEDI': {210332: 0.9901},
 'YEARS_BUILD_MEDI': {210332: 0.7585},
 'COMMONAREA_MEDI': {210332: 0.0223},
 'ELEVATORS_MEDI': {210332: 0.36},
 'ENTRANCES_MEDI': {210332: 0.3103},
 'FLOORSMAX_MEDI': {210332: 0.375},
 'FLOORSMIN_MEDI': {210332: 0.2083},
 'LANDAREA_MEDI': {210332: 0.0488},
 'LIVINGAPARTMENTS_MEDI': {210332: 0.077},
 'LIVINGAREA_MEDI': {210332: 0.3989},
 'NONLIVINGAPARTMENTS_MEDI': {210332: 0.0},
 'NONLIVINGAREA_MEDI': {210332: 0.2204},
 'TOTALAREA_MODE': {210332: 0.3498},
 'OBS_30_CNT_SOCIAL_CIRCLE': {210332: 0.0},
 'DEF_30_CNT_SOCIAL_CIRCLE': {210332: 0.0},
 'OBS_60_CNT_SOCIAL_CIRCLE': {210332: 0.0},
 'DEF_60_CNT_SOCIAL_CIRCLE': {210332: 0.0},
 'DAYS_LAST_PHONE_CHANGE': {210332: -1984.0},
 'FLAG_DOCUMENT_2': {210332: 0.0},
 'FLAG_DOCUMENT_3': {210332: 1.0},
 'FLAG_DOCUMENT_4': {210332: 0.0},
 'FLAG_DOCUMENT_5': {210332: 0.0},
 'FLAG_DOCUMENT_6': {210332: 0.0},
 'FLAG_DOCUMENT_7': {210332: 0.0},
 'FLAG_DOCUMENT_8': {210332: 0.0},
 'FLAG_DOCUMENT_9': {210332: 0.0},
 'FLAG_DOCUMENT_10': {210332: 0.0},
 'FLAG_DOCUMENT_11': {210332: 0.0},
 'FLAG_DOCUMENT_12': {210332: 0.0},
 'FLAG_DOCUMENT_13': {210332: 0.0},
 'FLAG_DOCUMENT_14': {210332: 0.0},
 'FLAG_DOCUMENT_15': {210332: 0.0},
 'FLAG_DOCUMENT_16': {210332: 0.0},
 'FLAG_DOCUMENT_17': {210332: 0.0},
 'FLAG_DOCUMENT_18': {210332: 0.0},
 'FLAG_DOCUMENT_19': {210332: 0.0},
 'FLAG_DOCUMENT_20': {210332: 0.0},
 'FLAG_DOCUMENT_21': {210332: 0.0},
 'AMT_REQ_CREDIT_BUREAU_HOUR': {210332: 0.0},
 'AMT_REQ_CREDIT_BUREAU_DAY': {210332: 0.0},
 'AMT_REQ_CREDIT_BUREAU_WEEK': {210332: 0.0},
 'AMT_REQ_CREDIT_BUREAU_MON': {210332: 0.0},
 'AMT_REQ_CREDIT_BUREAU_QRT': {210332: 1.0},
 'AMT_REQ_CREDIT_BUREAU_YEAR': {210332: 5.0},
 'NAME_CONTRACT_TYPE_Cash loans': {210332: 1.0},
 'NAME_CONTRACT_TYPE_Revolving loans': {210332: 0.0},
 'NAME_TYPE_SUITE_Children': {210332: 0.0},
 'NAME_TYPE_SUITE_Family': {210332: 0.0},
 'NAME_TYPE_SUITE_Group of people': {210332: 0.0},
 'NAME_TYPE_SUITE_Other_A': {210332: 0.0},
 'NAME_TYPE_SUITE_Other_B': {210332: 0.0},
 'NAME_TYPE_SUITE_Spouse, partner': {210332: 0.0},
 'NAME_TYPE_SUITE_Unaccompanied': {210332: 1.0},
 'NAME_INCOME_TYPE_Businessman': {210332: 0.0},
 'NAME_INCOME_TYPE_Commercial associate': {210332: 0.0},
 'NAME_INCOME_TYPE_Maternity leave': {210332: 0.0},
 'NAME_INCOME_TYPE_Pensioner': {210332: 0.0},
 'NAME_INCOME_TYPE_State servant': {210332: 1.0},
 'NAME_INCOME_TYPE_Student': {210332: 0.0},
 'NAME_INCOME_TYPE_Unemployed': {210332: 0.0},
 'NAME_INCOME_TYPE_Working': {210332: 0.0},
 'NAME_EDUCATION_TYPE_Academic degree': {210332: 0.0},
 'NAME_EDUCATION_TYPE_Higher education': {210332: 1.0},
 'NAME_EDUCATION_TYPE_Incomplete higher': {210332: 0.0},
 'NAME_EDUCATION_TYPE_Lower secondary': {210332: 0.0},
 'NAME_EDUCATION_TYPE_Secondary / secondary special': {210332: 0.0},
 'NAME_FAMILY_STATUS_Civil marriage': {210332: 0.0},
 'NAME_FAMILY_STATUS_Married': {210332: 1.0},
 'NAME_FAMILY_STATUS_Separated': {210332: 0.0},
 'NAME_FAMILY_STATUS_Single / not married': {210332: 0.0},
 'NAME_FAMILY_STATUS_Unknown': {210332: 0.0},
 'NAME_FAMILY_STATUS_Widow': {210332: 0.0},
 'NAME_HOUSING_TYPE_Co-op apartment': {210332: 0.0},
 'NAME_HOUSING_TYPE_House / apartment': {210332: 1.0},
 'NAME_HOUSING_TYPE_Municipal apartment': {210332: 0.0},
 'NAME_HOUSING_TYPE_Office apartment': {210332: 0.0},
 'NAME_HOUSING_TYPE_Rented apartment': {210332: 0.0},
 'NAME_HOUSING_TYPE_With parents': {210332: 0.0},
 'OCCUPATION_TYPE_Accountants': {210332: 0.0},
 'OCCUPATION_TYPE_Cleaning staff': {210332: 0.0},
 'OCCUPATION_TYPE_Cooking staff': {210332: 0.0},
 'OCCUPATION_TYPE_Core staff': {210332: 1.0},
 'OCCUPATION_TYPE_Drivers': {210332: 0.0},
 'OCCUPATION_TYPE_HR staff': {210332: 0.0},
 'OCCUPATION_TYPE_High skill tech staff': {210332: 0.0},
 'OCCUPATION_TYPE_IT staff': {210332: 0.0},
 'OCCUPATION_TYPE_Laborers': {210332: 0.0},
 'OCCUPATION_TYPE_Low-skill Laborers': {210332: 0.0},
 'OCCUPATION_TYPE_Managers': {210332: 0.0},
 'OCCUPATION_TYPE_Medicine staff': {210332: 0.0},
 'OCCUPATION_TYPE_Private service staff': {210332: 0.0},
 'OCCUPATION_TYPE_Realty agents': {210332: 0.0},
 'OCCUPATION_TYPE_Sales staff': {210332: 0.0},
 'OCCUPATION_TYPE_Secretaries': {210332: 0.0},
 'OCCUPATION_TYPE_Security staff': {210332: 0.0},
 'OCCUPATION_TYPE_Waiters/barmen staff': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_FRIDAY': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_MONDAY': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_SATURDAY': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_SUNDAY': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_THURSDAY': {210332: 1.0},
 'WEEKDAY_APPR_PROCESS_START_TUESDAY': {210332: 0.0},
 'WEEKDAY_APPR_PROCESS_START_WEDNESDAY': {210332: 0.0},
 'ORGANIZATION_TYPE_Advertising': {210332: 0.0},
 'ORGANIZATION_TYPE_Agriculture': {210332: 0.0},
 'ORGANIZATION_TYPE_Bank': {210332: 0.0},
 'ORGANIZATION_TYPE_Business Entity Type 1': {210332: 0.0},
 'ORGANIZATION_TYPE_Business Entity Type 2': {210332: 0.0},
 'ORGANIZATION_TYPE_Business Entity Type 3': {210332: 0.0},
 'ORGANIZATION_TYPE_Cleaning': {210332: 0.0},
 'ORGANIZATION_TYPE_Construction': {210332: 0.0},
 'ORGANIZATION_TYPE_Culture': {210332: 0.0},
 'ORGANIZATION_TYPE_Electricity': {210332: 0.0},
 'ORGANIZATION_TYPE_Emergency': {210332: 0.0},
 'ORGANIZATION_TYPE_Government': {210332: 0.0},
 'ORGANIZATION_TYPE_Hotel': {210332: 0.0},
 'ORGANIZATION_TYPE_Housing': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 1': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 10': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 11': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 12': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 13': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 2': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 3': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 4': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 5': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 6': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 7': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 8': {210332: 0.0},
 'ORGANIZATION_TYPE_Industry: type 9': {210332: 0.0},
 'ORGANIZATION_TYPE_Insurance': {210332: 0.0},
 'ORGANIZATION_TYPE_Kindergarten': {210332: 0.0},
 'ORGANIZATION_TYPE_Legal Services': {210332: 0.0},
 'ORGANIZATION_TYPE_Medicine': {210332: 1.0},
 'ORGANIZATION_TYPE_Military': {210332: 0.0},
 'ORGANIZATION_TYPE_Mobile': {210332: 0.0},
 'ORGANIZATION_TYPE_Other': {210332: 0.0},
 'ORGANIZATION_TYPE_Police': {210332: 0.0},
 'ORGANIZATION_TYPE_Postal': {210332: 0.0},
 'ORGANIZATION_TYPE_Realtor': {210332: 0.0},
 'ORGANIZATION_TYPE_Religion': {210332: 0.0},
 'ORGANIZATION_TYPE_Restaurant': {210332: 0.0},
 'ORGANIZATION_TYPE_School': {210332: 0.0},
 'ORGANIZATION_TYPE_Security': {210332: 0.0},
 'ORGANIZATION_TYPE_Security Ministries': {210332: 0.0},
 'ORGANIZATION_TYPE_Self-employed': {210332: 0.0},
 'ORGANIZATION_TYPE_Services': {210332: 0.0},
 'ORGANIZATION_TYPE_Telecom': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 1': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 2': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 3': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 4': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 5': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 6': {210332: 0.0},
 'ORGANIZATION_TYPE_Trade: type 7': {210332: 0.0},
 'ORGANIZATION_TYPE_Transport: type 1': {210332: 0.0},
 'ORGANIZATION_TYPE_Transport: type 2': {210332: 0.0},
 'ORGANIZATION_TYPE_Transport: type 3': {210332: 0.0},
 'ORGANIZATION_TYPE_Transport: type 4': {210332: 0.0},
 'ORGANIZATION_TYPE_University': {210332: 0.0},
 'ORGANIZATION_TYPE_XNA': {210332: 0.0},
 'FONDKAPREMONT_MODE_not specified': {210332: 0.0},
 'FONDKAPREMONT_MODE_org spec account': {210332: 0.0},
 'FONDKAPREMONT_MODE_reg oper account': {210332: 0.0},
 'FONDKAPREMONT_MODE_reg oper spec account': {210332: 0.0},
 'HOUSETYPE_MODE_block of flats': {210332: 1.0},
 'HOUSETYPE_MODE_specific housing': {210332: 0.0},
 'HOUSETYPE_MODE_terraced house': {210332: 0.0},
 'WALLSMATERIAL_MODE_Block': {210332: 0.0},
 'WALLSMATERIAL_MODE_Mixed': {210332: 0.0},
 'WALLSMATERIAL_MODE_Monolithic': {210332: 0.0},
 'WALLSMATERIAL_MODE_Others': {210332: 0.0},
 'WALLSMATERIAL_MODE_Panel': {210332: 0.0},
 'WALLSMATERIAL_MODE_Stone, brick': {210332: 1.0},
 'WALLSMATERIAL_MODE_Wooden': {210332: 0.0},
 'EMERGENCYSTATE_MODE_No': {210332: 1.0},
 'EMERGENCYSTATE_MODE_Yes': {210332: 0.0},
 'DAYS_EMPLOYED_PERC': {210332: 0.2257691623688422},
 'INCOME_CREDIT_PERC': {210332: 0.8},
 'INCOME_PER_PERSON': {210332: 270000.0},
 'ANNUITY_INCOME_PERC': {210332: 0.1312583333333333},
 'PAYMENT_RATE': {210332: 0.1050066666666666},
 'BURO_DAYS_CREDIT_MIN': {210332: -912.0},
 'BURO_DAYS_CREDIT_MAX': {210332: -166.0},
 'BURO_DAYS_CREDIT_MEAN': {210332: -539.0},
 'BURO_DAYS_CREDIT_VAR': {210332: 278258.0},
 'BURO_DAYS_CREDIT_ENDDATE_MIN': {210332: 182.0},
 'BURO_DAYS_CREDIT_ENDDATE_MAX': {210332: 930.0},
 'BURO_DAYS_CREDIT_ENDDATE_MEAN': {210332: 556.0},
 'BURO_DAYS_CREDIT_UPDATE_MEAN': {210332: -77.0},
 'BURO_CREDIT_DAY_OVERDUE_MAX': {210332: 0.0},
 'BURO_CREDIT_DAY_OVERDUE_MEAN': {210332: 0.0},
 'BURO_AMT_CREDIT_MAX_OVERDUE_MEAN': {210332: 50602.5},
 'BURO_AMT_CREDIT_SUM_MAX': {210332: 2824465.5},
 'BURO_AMT_CREDIT_SUM_MEAN': {210332: 2117767.5},
 'BURO_AMT_CREDIT_SUM_SUM': {210332: 4235535.0},
 'BURO_AMT_CREDIT_SUM_DEBT_MAX': {210332: 174766.5},
 'BURO_AMT_CREDIT_SUM_DEBT_MEAN': {210332: 48344.75},
 'BURO_AMT_CREDIT_SUM_DEBT_SUM': {210332: 0.0},
 'BURO_AMT_CREDIT_SUM_OVERDUE_MEAN': {210332: 0.0},
 'BURO_AMT_CREDIT_SUM_LIMIT_MEAN': {210332: 0.0},
 'BURO_AMT_CREDIT_SUM_LIMIT_SUM': {210332: 0.0},
 'BURO_AMT_ANNUITY_MAX': {210332: 39196.395},
 'BURO_AMT_ANNUITY_MEAN': {210332: 19598.1975},
 'BURO_CNT_CREDIT_PROLONG_SUM': {210332: 0.0},
 'BURO_MONTHS_BALANCE_MIN_MIN': {210332: -30.0},
 'BURO_MONTHS_BALANCE_MAX_MAX': {210332: 0.0},
 'BURO_MONTHS_BALANCE_SIZE_MEAN': {210332: 18.5},
 'BURO_MONTHS_BALANCE_SIZE_SUM': {210332: 37.0},
 'BURO_CREDIT_ACTIVE_Active_MEAN': {210332: 1.0},
 'BURO_CREDIT_ACTIVE_Bad debt_MEAN': {210332: 0.0},
 'BURO_CREDIT_ACTIVE_Closed_MEAN': {210332: 0.0},
 'BURO_CREDIT_ACTIVE_Sold_MEAN': {210332: 0.0},
 'BURO_CREDIT_CURRENCY_currency 1_MEAN': {210332: 1.0},
 'BURO_CREDIT_CURRENCY_currency 2_MEAN': {210332: 0.0},
 'BURO_CREDIT_CURRENCY_currency 3_MEAN': {210332: 0.0},
 'BURO_CREDIT_CURRENCY_currency 4_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Another type of loan_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Car loan_MEAN': {210332: 1.0},
 'BURO_CREDIT_TYPE_Cash loan (non-earmarked)_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Consumer credit_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Credit card_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Interbank credit_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Loan for business development_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Loan for purchase of shares (margin lending)_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Loan for the purchase of equipment_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Loan for working capital replenishment_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Microloan_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Mobile operator loan_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Mortgage_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Real estate loan_MEAN': {210332: 0.0},
 'BURO_CREDIT_TYPE_Unknown type of loan_MEAN': {210332: 0.0},
 'BURO_STATUS_0_MEAN_MEAN': {210332: 0.7553763440860215},
 'BURO_STATUS_1_MEAN_MEAN': {210332: 0.0806451612903225},
 'BURO_STATUS_2_MEAN_MEAN': {210332: 0.0},
 'BURO_STATUS_3_MEAN_MEAN': {210332: 0.0},
 'BURO_STATUS_4_MEAN_MEAN': {210332: 0.0},
 'BURO_STATUS_5_MEAN_MEAN': {210332: 0.0},
 'BURO_STATUS_C_MEAN_MEAN': {210332: 0.0},
 'BURO_STATUS_X_MEAN_MEAN': {210332: 0.1639784946236559},
 'ACTIVE_DAYS_CREDIT_MIN': {210332: -912.0},
 'ACTIVE_DAYS_CREDIT_MAX': {210332: -166.0},
 'ACTIVE_DAYS_CREDIT_MEAN': {210332: -539.0},
 'ACTIVE_DAYS_CREDIT_VAR': {210332: 278258.0},
 'ACTIVE_DAYS_CREDIT_ENDDATE_MIN': {210332: 182.0},
 'ACTIVE_DAYS_CREDIT_ENDDATE_MAX': {210332: 930.0},
 'ACTIVE_DAYS_CREDIT_ENDDATE_MEAN': {210332: 556.0},
 'ACTIVE_DAYS_CREDIT_UPDATE_MEAN': {210332: -77.0},
 'ACTIVE_CREDIT_DAY_OVERDUE_MAX': {210332: 0.0},
 'ACTIVE_CREDIT_DAY_OVERDUE_MEAN': {210332: 0.0},
 'ACTIVE_AMT_CREDIT_MAX_OVERDUE_MEAN': {210332: 50602.5},
 'ACTIVE_AMT_CREDIT_SUM_MAX': {210332: 2824465.5},
 'ACTIVE_AMT_CREDIT_SUM_MEAN': {210332: 2117767.5},
 'ACTIVE_AMT_CREDIT_SUM_SUM': {210332: 4235535.0},
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MAX': {210332: 276012.0},
 'ACTIVE_AMT_CREDIT_SUM_DEBT_MEAN': {210332: 169023.0},
 'ACTIVE_AMT_CREDIT_SUM_DEBT_SUM': {210332: 0.0},
 'ACTIVE_AMT_CREDIT_SUM_OVERDUE_MEAN': {210332: 0.0},
 'ACTIVE_AMT_CREDIT_SUM_LIMIT_MEAN': {210332: 0.0},
 'ACTIVE_AMT_CREDIT_SUM_LIMIT_SUM': {210332: 0.0},
 'ACTIVE_AMT_ANNUITY_MAX': {210332: 39196.395},
 'ACTIVE_AMT_ANNUITY_MEAN': {210332: 19598.1975},
 'ACTIVE_CNT_CREDIT_PROLONG_SUM': {210332: 0.0},
 'ACTIVE_MONTHS_BALANCE_MIN_MIN': {210332: -30.0},
 'ACTIVE_MONTHS_BALANCE_MAX_MAX': {210332: 0.0},
 'ACTIVE_MONTHS_BALANCE_SIZE_MEAN': {210332: 18.5},
 'ACTIVE_MONTHS_BALANCE_SIZE_SUM': {210332: 37.0},
 'CLOSED_DAYS_CREDIT_MIN': {210332: -1895.0},
 'CLOSED_DAYS_CREDIT_MAX': {210332: -717.5},
 'CLOSED_DAYS_CREDIT_MEAN': {210332: -1338.2916666666663},
 'CLOSED_DAYS_CREDIT_VAR': {210332: 300900.4484848485},
 'CLOSED_DAYS_CREDIT_ENDDATE_MIN': {210332: -1418.0},
 'CLOSED_DAYS_CREDIT_ENDDATE_MAX': {210332: -186.0},
 'CLOSED_DAYS_CREDIT_ENDDATE_MEAN': {210332: -748.3333333333334},
 'CLOSED_DAYS_CREDIT_UPDATE_MEAN': {210332: -740.0},
 'CLOSED_CREDIT_DAY_OVERDUE_MAX': {210332: 0.0},
 'CLOSED_CREDIT_DAY_OVERDUE_MEAN': {210332: 0.0},
 'CLOSED_AMT_CREDIT_MAX_OVERDUE_MEAN': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_MAX': {210332: 226165.635},
 'CLOSED_AMT_CREDIT_SUM_MEAN': {210332: 133903.75},
 'CLOSED_AMT_CREDIT_SUM_SUM': {210332: 474561.72},
 'CLOSED_AMT_CREDIT_SUM_DEBT_MAX': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_DEBT_MEAN': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_DEBT_SUM': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_OVERDUE_MEAN': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_LIMIT_MEAN': {210332: 0.0},
 'CLOSED_AMT_CREDIT_SUM_LIMIT_SUM': {210332: 0.0},
 'CLOSED_AMT_ANNUITY_MAX': {210332: 0.0},
 'CLOSED_AMT_ANNUITY_MEAN': {210332: 0.0},
 'CLOSED_CNT_CREDIT_PROLONG_SUM': {210332: 0.0},
 'CLOSED_MONTHS_BALANCE_MIN_MIN': {210332: -62.0},
 'CLOSED_MONTHS_BALANCE_MAX_MAX': {210332: 0.0},
 'CLOSED_MONTHS_BALANCE_SIZE_MEAN': {210332: 44.5},
 'CLOSED_MONTHS_BALANCE_SIZE_SUM': {210332: 142.0},
 'PREV_AMT_ANNUITY_MIN': {210332: 11015.19},
 'PREV_AMT_ANNUITY_MAX': {210332: 22500.0},
 'PREV_AMT_ANNUITY_MEAN': {210332: 13851.9525},
 'PREV_AMT_APPLICATION_MIN': {210332: 0.0},
 'PREV_AMT_APPLICATION_MAX': {210332: 112500.0},
 'PREV_AMT_APPLICATION_MEAN': {210332: 65250.0},
 'PREV_AMT_CREDIT_MIN': {210332: 105534.0},
 'PREV_AMT_CREDIT_MAX': {210332: 450000.0},
 'PREV_AMT_CREDIT_MEAN': {210332: 186435.0},
 'PREV_APP_CREDIT_PERC_MIN': {210332: 0.0},
 'PREV_APP_CREDIT_PERC_MAX': {210332: 0.9380863039399624},
 'PREV_APP_CREDIT_PERC_MEAN': {210332: 0.587760803084899},
 'PREV_APP_CREDIT_PERC_VAR': {210332: 0.2098527566243816},
 'PREV_AMT_DOWN_PAYMENT_MIN': {210332: 0.0},
 'PREV_AMT_DOWN_PAYMENT_MAX': {210332: 0.0},
 'PREV_AMT_DOWN_PAYMENT_MEAN': {210332: 0.0},
 'PREV_AMT_GOODS_PRICE_MIN': {210332: 0.0},
 'PREV_AMT_GOODS_PRICE_MAX': {210332: 112500.0},
 'PREV_AMT_GOODS_PRICE_MEAN': {210332: 78300.0},
 'PREV_HOUR_APPR_PROCESS_START_MIN': {210332: 12.0},
 'PREV_HOUR_APPR_PROCESS_START_MAX': {210332: 14.0},
 'PREV_HOUR_APPR_PROCESS_START_MEAN': {210332: 12.333333333333334},
 'PREV_RATE_DOWN_PAYMENT_MIN': {210332: 0.0},
 'PREV_RATE_DOWN_PAYMENT_MAX': {210332: 0.0},
 'PREV_RATE_DOWN_PAYMENT_MEAN': {210332: 0.0},
 'PREV_DAYS_DECISION_MIN': {210332: -1984.0},
 'PREV_DAYS_DECISION_MAX': {210332: -1060.0},
 'PREV_DAYS_DECISION_MEAN': {210332: -1455.0},
 'PREV_CNT_PAYMENT_MEAN': {210332: 8.0},
 'PREV_CNT_PAYMENT_SUM': {210332: 48.0},
 'PREV_NAME_CONTRACT_TYPE_Cash loans_MEAN': {210332: 0.6666666666666666},
 'PREV_NAME_CONTRACT_TYPE_Consumer loans_MEAN': {210332: 0.0},
 'PREV_NAME_CONTRACT_TYPE_Revolving loans_MEAN': {210332: 0.3333333333333333},
 'PREV_NAME_CONTRACT_TYPE_XNA_MEAN': {210332: 0.0},
 'PREV_WEEKDAY_APPR_PROCESS_START_FRIDAY_MEAN': {210332: 0.1666666666666666},
 'PREV_WEEKDAY_APPR_PROCESS_START_MONDAY_MEAN': {210332: 0.1666666666666666},
 'PREV_WEEKDAY_APPR_PROCESS_START_SATURDAY_MEAN': {210332: 0.0},
 'PREV_WEEKDAY_APPR_PROCESS_START_SUNDAY_MEAN': {210332: 0.0},
 'PREV_WEEKDAY_APPR_PROCESS_START_THURSDAY_MEAN': {210332: 0.0},
 'PREV_WEEKDAY_APPR_PROCESS_START_TUESDAY_MEAN': {210332: 0.5},
 'PREV_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_MEAN': {210332: 0.1666666666666666},
 'PREV_FLAG_LAST_APPL_PER_CONTRACT_N_MEAN': {210332: 0.0},
 'PREV_FLAG_LAST_APPL_PER_CONTRACT_Y_MEAN': {210332: 1.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Building a house or an annex_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Business development_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a garage_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a holiday home / land_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a home_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a new car_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Buying a used car_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Car repairs_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Education_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Everyday expenses_MEAN': {210332: 0.0},
 'PREV_NAME_CASH_LOAN_PURPOSE_Furniture_MEAN': {210332: 0.0},

In [21]:
ID = 210332

In [31]:
data_json = {'data': ID}

In [32]:
response = requests.request(
        method='POST', url="http://127.0.0.1:8000/invocations", json=data_json)

In [33]:
response